kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ template "cello-master.fullname" . }}-mongo"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mongo.size }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
