{{- if .Values.mongo.storeEnabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "cello-master.mongo.pvName" . }}
  labels:
    type: local
spec:
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  capacity:
    storage: {{ .Values.mongo.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.mongo.storePath }}
{{- end }}