kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cello-master.mongo.pvName" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mongo.size }}