kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ template "cello-master.fullname" . }}-nfs"
spec:
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
